#!/bin/bash

mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
# repo init -q --no-repo-verify --depth=1 -u git://github.com/AospExtended/manifest.git -b 11.x -g default,-device,-mips,-darwin,-notdefault
repo init --no-repo-verify --depth=1 -u https://github.com/ArcaneOS/Arcane_manifest.git -b R -g default,-device,-mips,-darwin,-notdefault

# Clone local manifest! So that no need to manually git clone repos or change hals, you can use normal git clone or rm and re clone, they will cost little more time, and you may get timeout! Let's make it quit and depth=1 too.
# git clone https://github.com/Apon77Lab/android_.repo_local_manifests.git --depth 1 -b aex .repo/local_manifests

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j18 and then -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 30 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 16 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 8

# Sync Device Specific repos, another way is to define a local repo manifest. as in line #11 
git clone https://github.com/felapr1804/android_device_xiaomi_raphael.git -b eleven device/xiaomi/raphael
git clone https://github.com/Evolution-X-Devices/vendor_xiaomi_raphael.git -b elle vendor/xiaomi/raphael

git clone https://github.com/Alchemist-xD/android_kernel_xiaomi_raphael.git kernel/xiaomi/raphael
