#!/bin/bash

cd /tmp

# Compress function with pigz for faster compression
com () 
{ 
    tar --use-compress-program="pigz -k -$2 " -cf $1.tar.gz $1
}

time com ccache 1 # Compression level 1, its enough

up(){
	curl --upload-file $1 https://transfer.sh/$(echo $RANDOM | base64 | head -c 20)ccache; echo
	# 14 days, 10 GB limit
}

# mkdir -p ~/.config/rclone
# echo "$rclone_config" > ~/.config/rclone/rclone.conf # Write rclone config found from env variable, so that cloud storage can be used to upload ccache
# time rclone copy ccache.tar.gz apon:ccache/ci2 -P # apon is my rclone config name (first line without [] of ~/.config/rclone/rclone.conf file from rclone setupped pc), ccache/ci2 is where ccache will be saved in my cloud, use yours one
du -hs ccache.tar.gz
time up ccache.tar.gz